### ISSUE TITLE
Попробуйте запустить на большом файле

### ISSUE THREAD

**Issue by egor1989** [SacredArrow/baltinfocom_test#1]
https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

**Comment by SacredArrow** [comment]
@egor1989 вышло 334387 групп, время работы около 25с. Лог по [ссылке](https://drive.google.com/file/d/1aPhmXSSDWMf4DsxkV5cN4FlXcNKKTgA8/view?usp=sharing).

**Comment by egor1989** [comment]
@SacredArrow это неверный ответ

**Comment by SacredArrow** [comment]
@egor1989 Пардон, нашел баг. 105036 групп теперь получилось. Новый [лог](https://drive.google.com/file/d/1H9LyXyX58FxrQFgrytugJ6joN3w4uUlo/view?usp=sharing).

**Comment by egor1989** [comment]
@SacredArrow в чем заключался баг? Опишите словами и/или схематично ваш алгоритм. Как он эволюционировал в процессе решения? Или вам сразу удалось найти правильный путь?

**Comment by SacredArrow** [comment]
@egor1989 Алгоритм такой - есть ноды (часть строки + позиция) и привязанные к ним строки. А также наоборот, строки и привязки к нодам. Перебираем ноды, если нода не была посещена, то пускаем из нее DFS. DFS смотрит на все привязанные к ноде строки, идет в привязанные к этим строкам ноды и так далее. Таким образом мы проводим поиск компонент связности в нашем графе. Кажая компонента - отдельная группа. То есть по сути, если мы берем в группу строку, то также берем все строки, у которых на тех же позициях те же подстроки. Баг был в том, что я перезаписывал запись в словаре, который строке сопоставлял ноды, в случае если дубликат такой строки уже встречался. То есть там была проверка, что был дубликат, но она стояла не в нужном месте и в итоге все равно происходила перезапись, на пустой список. 
Общая идея была понятна сразу - надо рекурсивно брать вместе со строкой все строки с совпадающими подстроками. Понемногу начала вырисовываться идея графа. Дальше осталось придумать, как его хранить и каким образом делать проход. В итоге все свелось к поиску компонент связности с некоторыми модификациями.

**Comment by SacredArrow** [comment]
@egor1989 увидели сообщение?

**Comment by egor1989** [comment]
ок, завтра в 15 ждем на собеседование
